### ISSUE TITLE
Add new attributes to field

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/mydig-webservice#1]
Need the following additional attributes:
- [ ] search_importance: an integer between 1 and 10
- [ ] use_in_network_search: Boolean

**Comment by GreatYYX** [comment]
Updated field object `city` in `dig3-ht` for testing.

**Comment by szeke** [comment]
Jason will need these attributes on all the fields to implement his part. Also, the GET for fields should return a list of the full field objects os that clients can get all the info in one call.
