### ISSUE TITLE
The screen label of tags is not recorded

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/mydig-webservice#13]
I created a tag, giving it a screen label, when I go to edit the tag, I don't see the screen label.

![2017-06-22_19-47-19](https://user-images.githubusercontent.com/1074599/27464678-9c33720e-5783-11e7-889a-bf6068444430.png)

**Comment by GSharayu** [comment]
Backend provides name as scree_label - so it was throwing empty string.

 For now, UI has been updated to scree_label.
