### ISSUE TITLE
Replace texts in myDIG page

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/mydig-webservice#25]
### Get Sample Pages
Retrieve sample pages from the CDR for testing your extractions. The sample will contain pages from each of your specified TLDs as well as a random selection of pages from other TLDs.

### Publish Project Files
Upload all the project files to the myDIG protected GitHub repository, backing up your files to allow going to previous versions or preserving files in case of disk failure.

### Run Extractions and Load Index For Sample Pages
Run all extractors currently defined and load the extracted data into a new ElasticSearch index. You need to perform the Update To New Index command to replace your current index with the new index. Important: wait for this command to show Running: false before clicking Update To New Index

### Update To New Index
Update the search engine to use the latest ElasticSearch index. Important: you need to select the Reload the DIG Configuration in the DIG app to synchronize it to the latest index.

**Comment by GreatYYX** [comment]
Now there's no `Running: False` in GUI, need to update the description for `Run Extractions and Load Index For Sample Pages`.
