### ISSUE TITLE
Add `combined_field` attribute to fields

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/mydig-webservice#3]
The the value of the `combined_field` attribute is the name of a field that will appear in the query form., and can be used as a predicate in queries.

Suppose I have several fields such as `address`, `city`, `state`, `country` and I want the search form to have a `location` field where a user can type any part of a location. What I do is I put `"combined_field": "location"` as a attribute of each of `address`, `city`, `state`, `country`. 

I can choose to have `address`, `city`, `state`, `country` or have them disappear from the query form. To do that I use the `show_in_search` attribute in these fields, setting it to true/false as desired.

**Comment by ThomasSchellenbergNextCentury** [comment]
Will each `combined_field` have its own property in the `knowledge_graph`?  Continuing your example:
```
knowledge_graph: {
  address: { ... },
  city: { ... },
  country: { ... },
  location: { ... },
  state: { .. }
}
```

If so, I don't think the DIG UI cares if a field is a `combined_field` or not, as long as the user specifies a `format` in the field config.

**Comment by szeke** [comment]
@jasonslepicka the `combine_field` feature is lower priority than generating the mapping files directly from the service
