### ISSUE TITLE
Tooltips should not obscure the field that the user is typing in the field editor

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/mydig-webservice#33]
Currently, when I click on a type in box in the field editor, the tooltip appears on the box and doesn't let me see what I am typing. I have to move the mouse to make the tooltip go away.

**Comment by GSharayu** [comment]
Type Field has dropdown. Tooltip focuses on Mouse pointer. As of now, I am not clear on issue.Mouse pointer needs to change for making tooltip go away. Dropdown menu is not affected.
Please clear out
