### ISSUE TITLE
Add Edit Rules button (after renaming current Edit Rules to Upload Rules

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/mydig-webservice#42]
The new Edit Rules button should invoke URL like this
`http://xnet.nextcentury.com/wiser/spacy/#/52.36.12.77:9879/wole/bitcoin`

so it is 
`http://xnet.nextcentury.com/wiser/spacy/#/52.36.12.77:9879/<project-name>/<field-name>`

**Comment by GreatYYX** [comment]
@GSharayu the backend url changed. now it should point to `http://35.160.106.225:9879/`

**Comment by GreatYYX** [comment]
@GSharayu my suggestion is, for our url, try to get it by javascript, do not hard code it. (I think backend and frontend will be on the same server for a long time).

**Comment by szeke** [comment]
The URL to the graphical rule editor is currently on a machine at next century.
The ip address should not be hard coded. If there is no way to get it currently, then hard code it for now.
