### ISSUE TITLE
Project edit dialog shows incorrect fields

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/mydig-webservice#8]
The edit fields in the project edit dialog don't match the fields in the create project dialog.
[ ] There is no way to edit the TLDs
[ ] The index name is not being shown
[ ] The start and end date fields have no labels
[ ]  Query should not be there
[ ] The `root name` does not match

![2017-06-22_19-21-27](https://user-images.githubusercontent.com/1074599/27464052-01a69728-5780-11e7-8d74-0dd752214704.png)

**Comment by GSharayu** [comment]
Test with new Commit
