### ISSUE TITLE
When I reload `http://52.36.12.77:9880/` all the projects disappeared

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/mydig-webservice#9]
Here is what I get

![2017-06-22_19-23-16](https://user-images.githubusercontent.com/1074599/27464087-46b1367a-5780-11e7-909b-7d0ccc22d8c4.png)

**Comment by szeke** [comment]
If I add a new project, all the projects reappear

![2017-06-22_19-25-24](https://user-images.githubusercontent.com/1074599/27464131-8cbb5d44-5780-11e7-98ae-8370bff27e4e.png)

**Comment by GSharayu** [comment]
Not able to reproduce
